### ISSUE TITLE
Apply sql before and after migrations

### ISSUE THREAD

**Issue by pleshevskiy** [pleshevskiy/migra#13]
### Is your feature request related to a problem? Please describe.
In my daily work with the database, I need to run the script before and after migrations.

### Describe the solution you'd like
I'm thinking of giving the option to add an option to the manifest

```toml
[migrations]
exec_before = ["DROP SCHEMA IF EXISTS imp CASCADE;"]
apply_after_up = ["imp_schema"]
```

 and possibly options in cli

`migra up --before drop-schema --after imp-schema`
`migra down --exec-before "DROP SCHEMA IF EXISTS imp CASCADE;"`
